inputs:
- name: master
- name: version

outputs:
- name: build-artifact

platform: linux

image_resource:
  type: docker-image
  source:
    repository: tbatard/openjdk-8

run:
  dir: master
  path: sh
  args:
  - -c
  - |
    ./gradlew build
    cp build/libs/*.jar ../build-artifact/hello-spring-$(cat ../version/version).jar