inputs:
- name: master

outputs:
- name: build-artifact
  path: build/libs/pal-tracker.jar

platform: linux

image_resource:
  type: docker-image
  source:
    repository: tbatard/openjdk-8

run:
  dir: master
  path: sh
  args:
  - -exc
  - ./gradlew clean build