resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: cfcloudops/azure-blobstore-concourse-resource

resources:
- name: master
  type: git
  source:
    uri: git@github.com:tbatard/pal-tracker.git
    branch: master
    private_key: {{git-read-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:tbatard/pal-tracker.git
    branch: version
    file: version
    private_key: {{git-write-key}}
- name: build-artifacts
  type: azure-blobstore
  source:
    container: concourse
    storage_account_name: {{azure-storage-account-name}}
    storage_access_key: {{azure-storage-access-key}}
    regexp: builds/hello-spring-((\d\.){2}\d(-alpha\.\d){0,1}).jar
- name: acceptance
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: acceptance
    skip_cert_check: false

jobs:
- name: build
  serial: true
  plan:
  - get: master
    trigger: true
  - get: version
    params:
      pre: alpha
  - task: build
    file: master/ci/build.yml
  - put: build-artifacts
    params:
      file: ./build-artifact/hello-spring-*.jar
  - put: version
    params:
      file: version/version
- name: Acceptance
  serial: true
  plan:
  - get: master
    passed: [build]
  - get: build-artifacts
    passed: [build]
  - put: acceptance
    params:
      manifest: master/manifest.yml
      path: build-artifacts/hello-spring-*.jar
      environment_variables:
        WELCOME_MESSAGE: {{hello-spring-welcome-message}}
